//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Game_Render_RenderEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.Game.Render.RenderEvent), typeof(Sango.Singletion<Sango.Game.Render.RenderEvent>));
		L.RegFunction("Add", new LuaCSFunction(Add));
		L.RegFunction("Update", new LuaCSFunction(Update));
		L.RegFunction("New", new LuaCSFunction(_CreateSango_Game_Render_RenderEvent));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSango_Game_Render_RenderEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Sango.Game.Render.RenderEvent obj = new Sango.Game.Render.RenderEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Sango.Game.Render.RenderEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Add(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Render.RenderEvent obj = (Sango.Game.Render.RenderEvent)ToLua.CheckObject<Sango.Game.Render.RenderEvent>(L, 1);
			Sango.Game.Render.IRenderEventBase arg0 = (Sango.Game.Render.IRenderEventBase)ToLua.CheckObject<Sango.Game.Render.IRenderEventBase>(L, 2);
			obj.Add(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Sango.Game.Render.RenderEvent obj = (Sango.Game.Render.RenderEvent)ToLua.CheckObject<Sango.Game.Render.RenderEvent>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			bool o = obj.Update(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

