//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Game_Render_RenderEventBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.Game.Render.RenderEventBase), typeof(System.Object));
		L.RegFunction("IsVisible", new LuaCSFunction(IsVisible));
		L.RegFunction("Update", new LuaCSFunction(Update));
		L.RegFunction("Enter", new LuaCSFunction(Enter));
		L.RegFunction("Exit", new LuaCSFunction(Exit));
		L.RegFunction("New", new LuaCSFunction(_CreateSango_Game_Render_RenderEventBase));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("IsDone", new LuaCSFunction(get_IsDone), new LuaCSFunction(set_IsDone));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSango_Game_Render_RenderEventBase(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Sango.Game.Render.RenderEventBase obj = new Sango.Game.Render.RenderEventBase();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Sango.Game.Render.RenderEventBase.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsVisible(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Render.RenderEventBase obj = (Sango.Game.Render.RenderEventBase)ToLua.CheckObject<Sango.Game.Render.RenderEventBase>(L, 1);
			bool o = obj.IsVisible();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Sango.Game.Render.RenderEventBase obj = (Sango.Game.Render.RenderEventBase)ToLua.CheckObject<Sango.Game.Render.RenderEventBase>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			bool o = obj.Update(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Enter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Render.RenderEventBase obj = (Sango.Game.Render.RenderEventBase)ToLua.CheckObject<Sango.Game.Render.RenderEventBase>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.Enter(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Exit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Render.RenderEventBase obj = (Sango.Game.Render.RenderEventBase)ToLua.CheckObject<Sango.Game.Render.RenderEventBase>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.Exit(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsDone(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.RenderEventBase obj = (Sango.Game.Render.RenderEventBase)o;
			bool ret = obj.IsDone;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsDone on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_IsDone(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.RenderEventBase obj = (Sango.Game.Render.RenderEventBase)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.IsDone = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsDone on a nil value");
		}
	}
}

