//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Game_EventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.Game.GameEvent), typeof(Sango.EventBase));
		L.RegFunction("New", new LuaCSFunction(_CreateSango_Game_Event));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("OnGameStateEnter", new LuaCSFunction(get_OnGameStateEnter), new LuaCSFunction(set_OnGameStateEnter));
		L.RegVar("OnGameStateExit", new LuaCSFunction(get_OnGameStateExit), new LuaCSFunction(set_OnGameStateExit));
		L.RegVar("OnScenarioLoadStart", new LuaCSFunction(get_OnScenarioLoadStart), new LuaCSFunction(set_OnScenarioLoadStart));
		L.RegVar("OnScenarioLoadEnd", new LuaCSFunction(get_OnScenarioLoadEnd), new LuaCSFunction(set_OnScenarioLoadEnd));
		L.RegVar("OnWorldLoadStart", new LuaCSFunction(get_OnWorldLoadStart), new LuaCSFunction(set_OnWorldLoadStart));
		L.RegVar("OnWorldLoadEnd", new LuaCSFunction(get_OnWorldLoadEnd), new LuaCSFunction(set_OnWorldLoadEnd));
		L.RegVar("OnScenarioStart", new LuaCSFunction(get_OnScenarioStart), new LuaCSFunction(set_OnScenarioStart));
		L.RegVar("OnScenarioPrepare", new LuaCSFunction(get_OnScenarioPrepare), new LuaCSFunction(set_OnScenarioPrepare));
		L.RegVar("OnScenarioEnd", new LuaCSFunction(get_OnScenarioEnd), new LuaCSFunction(set_OnScenarioEnd));
		L.RegVar("OnScenarioTick", new LuaCSFunction(get_OnScenarioTick), new LuaCSFunction(set_OnScenarioTick));
		L.RegVar("OnWindowCreate", new LuaCSFunction(get_OnWindowCreate), new LuaCSFunction(set_OnWindowCreate));
		L.RegVar("OnSelectBattle", new LuaCSFunction(get_OnSelectBattle), new LuaCSFunction(set_OnSelectBattle));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSango_Game_Event(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Sango.Game.GameEvent obj = new Sango.Game.GameEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Sango.Game.Event.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnGameStateEnter(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnGameStateEnter);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnGameStateExit(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnGameStateExit);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnScenarioLoadStart(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnScenarioLoadStart);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnScenarioLoadEnd(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnScenarioLoadEnd);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnWorldLoadStart(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnWorldLoadStart);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnWorldLoadEnd(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnWorldLoadEnd);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnScenarioStart(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnScenarioStart);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnScenarioPrepare(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnScenarioPrepare);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnScenarioEnd(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnScenarioEnd);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnScenarioTick(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnScenarioTick);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnWindowCreate(IntPtr L)
	{
		try
		{
			ToLua.Push(L, Sango.Game.GameEvent.OnWindowCreate);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnSelectBattle(IntPtr L)
	{
		try
		{
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnGameStateEnter(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<int,int> arg0 = (Sango.EventBase.EventDelegate<int,int>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<int,int>>(L, 2);
			Sango.Game.GameEvent.OnGameStateEnter = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnGameStateEnter, arg0))
			{
				if (Sango.Game.GameEvent.OnGameStateEnter != null) Sango.Game.GameEvent.OnGameStateEnter.SubRef();
				Sango.Game.GameEvent.OnGameStateEnter = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnGameStateExit(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<int,int> arg0 = (Sango.EventBase.EventDelegate<int,int>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<int,int>>(L, 2);
			Sango.Game.GameEvent.OnGameStateExit = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnGameStateExit, arg0))
			{
				if (Sango.Game.GameEvent.OnGameStateExit != null) Sango.Game.GameEvent.OnGameStateExit.SubRef();
				Sango.Game.GameEvent.OnGameStateExit = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnScenarioLoadStart(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<Sango.Game.Scenario> arg0 = (Sango.EventBase.EventDelegate<Sango.Game.Scenario>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<Sango.Game.Scenario>>(L, 2);
			Sango.Game.GameEvent.OnScenarioLoadStart = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnScenarioLoadStart, arg0))
			{
				if (Sango.Game.GameEvent.OnScenarioLoadStart != null) Sango.Game.GameEvent.OnScenarioLoadStart.SubRef();
				Sango.Game.GameEvent.OnScenarioLoadStart = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnScenarioLoadEnd(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<Sango.Game.Scenario> arg0 = (Sango.EventBase.EventDelegate<Sango.Game.Scenario>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<Sango.Game.Scenario>>(L, 2);
			Sango.Game.GameEvent.OnScenarioLoadEnd = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnScenarioLoadEnd, arg0))
			{
				if (Sango.Game.GameEvent.OnScenarioLoadEnd != null) Sango.Game.GameEvent.OnScenarioLoadEnd.SubRef();
				Sango.Game.GameEvent.OnScenarioLoadEnd = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnWorldLoadStart(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<Sango.Game.Scenario> arg0 = (Sango.EventBase.EventDelegate<Sango.Game.Scenario>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<Sango.Game.Scenario>>(L, 2);
			Sango.Game.GameEvent.OnWorldLoadStart = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnWorldLoadStart, arg0))
			{
				if (Sango.Game.GameEvent.OnWorldLoadStart != null) Sango.Game.GameEvent.OnWorldLoadStart.SubRef();
				Sango.Game.GameEvent.OnWorldLoadStart = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnWorldLoadEnd(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<Sango.Game.Scenario> arg0 = (Sango.EventBase.EventDelegate<Sango.Game.Scenario>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<Sango.Game.Scenario>>(L, 2);
			Sango.Game.GameEvent.OnWorldLoadEnd = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnWorldLoadEnd, arg0))
			{
				if (Sango.Game.GameEvent.OnWorldLoadEnd != null) Sango.Game.GameEvent.OnWorldLoadEnd.SubRef();
				Sango.Game.GameEvent.OnWorldLoadEnd = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnScenarioStart(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<Sango.Game.Scenario> arg0 = (Sango.EventBase.EventDelegate<Sango.Game.Scenario>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<Sango.Game.Scenario>>(L, 2);
			Sango.Game.GameEvent.OnScenarioStart = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnScenarioStart, arg0))
			{
				if (Sango.Game.GameEvent.OnScenarioStart != null) Sango.Game.GameEvent.OnScenarioStart.SubRef();
				Sango.Game.GameEvent.OnScenarioStart = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnScenarioPrepare(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<Sango.Game.Scenario> arg0 = (Sango.EventBase.EventDelegate<Sango.Game.Scenario>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<Sango.Game.Scenario>>(L, 2);
			Sango.Game.GameEvent.OnScenarioPrepare = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnScenarioPrepare, arg0))
			{
				if (Sango.Game.GameEvent.OnScenarioPrepare != null) Sango.Game.GameEvent.OnScenarioPrepare.SubRef();
				Sango.Game.GameEvent.OnScenarioPrepare = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnScenarioEnd(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<Sango.Game.Scenario> arg0 = (Sango.EventBase.EventDelegate<Sango.Game.Scenario>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<Sango.Game.Scenario>>(L, 2);
			Sango.Game.GameEvent.OnScenarioEnd = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnScenarioEnd, arg0))
			{
				if (Sango.Game.GameEvent.OnScenarioEnd != null) Sango.Game.GameEvent.OnScenarioEnd.SubRef();
				Sango.Game.GameEvent.OnScenarioEnd = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnScenarioTick(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<Sango.Game.Scenario,float> arg0 = (Sango.EventBase.EventDelegate<Sango.Game.Scenario,float>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<Sango.Game.Scenario,float>>(L, 2);
			Sango.Game.GameEvent.OnScenarioTick = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnScenarioTick, arg0))
			{
				if (Sango.Game.GameEvent.OnScenarioTick != null) Sango.Game.GameEvent.OnScenarioTick.SubRef();
				Sango.Game.GameEvent.OnScenarioTick = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnWindowCreate(IntPtr L)
	{
		try
		{
			Sango.EventBase.EventDelegate<string,Sango.Window.WindowInterface> arg0 = (Sango.EventBase.EventDelegate<string,Sango.Window.WindowInterface>)ToLua.CheckDelegate<Sango.EventBase.EventDelegate<string,Sango.Window.WindowInterface>>(L, 2);
			Sango.Game.GameEvent.OnWindowCreate = arg0;

			if (!object.ReferenceEquals(Sango.Game.GameEvent.OnWindowCreate, arg0))
			{
				if (Sango.Game.GameEvent.OnWindowCreate != null) Sango.Game.GameEvent.OnWindowCreate.SubRef();
				Sango.Game.GameEvent.OnWindowCreate = arg0;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OnSelectBattle(IntPtr L)
	{
		try
		{
		
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

