//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Game_PersonWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.Game.Person), typeof(Sango.Game.SangoObject));
		L.RegFunction("HasItem", new LuaCSFunction(HasItem));
		L.RegFunction("OnPersonAgeUpdate", new LuaCSFunction(OnPersonAgeUpdate));
		L.RegFunction("IsAlliance", new LuaCSFunction(IsAlliance));
		L.RegFunction("IsEnemy", new LuaCSFunction(IsEnemy));
		L.RegFunction("IsSameForce", new LuaCSFunction(IsSameForce));
		L.RegFunction("OnScenarioPrepare", new LuaCSFunction(OnScenarioPrepare));
		L.RegFunction("OnYearStart", new LuaCSFunction(OnYearStart));
		L.RegFunction("UpdateMission", new LuaCSFunction(UpdateMission));
		L.RegFunction("SetMission", new LuaCSFunction(SetMission));
		L.RegFunction("ClearMission", new LuaCSFunction(ClearMission));
		L.RegFunction("OnNewTurn", new LuaCSFunction(OnNewTurn));
		L.RegFunction("OnTurnStart", new LuaCSFunction(OnTurnStart));
		L.RegFunction("TransformToCity", new LuaCSFunction(TransformToCity));
		L.RegFunction("ChangeCorps", new LuaCSFunction(ChangeCorps));
		L.RegFunction("ChangeCity", new LuaCSFunction(ChangeCity));
		L.RegFunction("JobRecuritPerson", new LuaCSFunction(JobRecuritPerson));
		L.RegFunction("JoinToForce", new LuaCSFunction(JoinToForce));
		L.RegFunction("LeaveToWild", new LuaCSFunction(LeaveToWild));
		L.RegFunction("Persuade", new LuaCSFunction(Persuade));
		L.RegFunction("BeCaptive", new LuaCSFunction(BeCaptive));
		L.RegFunction("GainExp", new LuaCSFunction(GainExp));
		L.RegFunction("New", new LuaCSFunction(_CreateSango_Game_Person));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("familyNameID", new LuaCSFunction(get_familyNameID), new LuaCSFunction(set_familyNameID));
		L.RegVar("familyName", new LuaCSFunction(get_familyName), new LuaCSFunction(set_familyName));
		L.RegVar("giveNameID", new LuaCSFunction(get_giveNameID), new LuaCSFunction(set_giveNameID));
		L.RegVar("giveName", new LuaCSFunction(get_giveName), new LuaCSFunction(set_giveName));
		L.RegVar("nickNameID", new LuaCSFunction(get_nickNameID), new LuaCSFunction(set_nickNameID));
		L.RegVar("nickName", new LuaCSFunction(get_nickName), new LuaCSFunction(set_nickName));
		L.RegVar("descriptionID", new LuaCSFunction(get_descriptionID), new LuaCSFunction(set_descriptionID));
		L.RegVar("description", new LuaCSFunction(get_description), new LuaCSFunction(set_description));
		L.RegVar("headIconID", new LuaCSFunction(get_headIconID), new LuaCSFunction(set_headIconID));
		L.RegVar("imageID", new LuaCSFunction(get_imageID), new LuaCSFunction(set_imageID));
		L.RegVar("sex", new LuaCSFunction(get_sex), new LuaCSFunction(set_sex));
		L.RegVar("yearAvailable", new LuaCSFunction(get_yearAvailable), new LuaCSFunction(set_yearAvailable));
		L.RegVar("beFinded", new LuaCSFunction(get_beFinded), new LuaCSFunction(set_beFinded));
		L.RegVar("yearBorn", new LuaCSFunction(get_yearBorn), new LuaCSFunction(set_yearBorn));
		L.RegVar("yearDead", new LuaCSFunction(get_yearDead), new LuaCSFunction(set_yearDead));
		L.RegVar("compatibility", new LuaCSFunction(get_compatibility), new LuaCSFunction(set_compatibility));
		L.RegVar("state", new LuaCSFunction(get_state), new LuaCSFunction(set_state));
		L.RegVar("loyalty", new LuaCSFunction(get_loyalty), new LuaCSFunction(set_loyalty));
		L.RegVar("merit", new LuaCSFunction(get_merit), new LuaCSFunction(set_merit));
		L.RegVar("command", new LuaCSFunction(get_command), new LuaCSFunction(set_command));
		L.RegVar("strength", new LuaCSFunction(get_strength), new LuaCSFunction(set_strength));
		L.RegVar("intelligence", new LuaCSFunction(get_intelligence), new LuaCSFunction(set_intelligence));
		L.RegVar("politics", new LuaCSFunction(get_politics), new LuaCSFunction(set_politics));
		L.RegVar("glamour", new LuaCSFunction(get_glamour), new LuaCSFunction(set_glamour));
		L.RegVar("consanguinity", new LuaCSFunction(get_consanguinity), new LuaCSFunction(set_consanguinity));
		L.RegVar("sonList", new LuaCSFunction(get_sonList), new LuaCSFunction(set_sonList));
		L.RegVar("spearLv", new LuaCSFunction(get_spearLv), new LuaCSFunction(set_spearLv));
		L.RegVar("halberdLv", new LuaCSFunction(get_halberdLv), new LuaCSFunction(set_halberdLv));
		L.RegVar("crossbowLv", new LuaCSFunction(get_crossbowLv), new LuaCSFunction(set_crossbowLv));
		L.RegVar("horseLv", new LuaCSFunction(get_horseLv), new LuaCSFunction(set_horseLv));
		L.RegVar("waterLv", new LuaCSFunction(get_waterLv), new LuaCSFunction(set_waterLv));
		L.RegVar("machineLv", new LuaCSFunction(get_machineLv), new LuaCSFunction(set_machineLv));
		L.RegVar("actionFlag", new LuaCSFunction(get_actionFlag), new LuaCSFunction(set_actionFlag));
		L.RegVar("FeatureList", new LuaCSFunction(get_FeatureList), new LuaCSFunction(set_FeatureList));
		L.RegVar("itemStore", new LuaCSFunction(get_itemStore), new LuaCSFunction(set_itemStore));
		L.RegVar("troopsLimitExtra", new LuaCSFunction(get_troopsLimitExtra), new LuaCSFunction(set_troopsLimitExtra));
		L.RegVar("skill", new LuaCSFunction(get_skill), new LuaCSFunction(set_skill));
		L.RegVar("missionType", new LuaCSFunction(get_missionType), new LuaCSFunction(set_missionType));
		L.RegVar("missionTarget", new LuaCSFunction(get_missionTarget), new LuaCSFunction(set_missionTarget));
		L.RegVar("missionCounter", new LuaCSFunction(get_missionCounter), new LuaCSFunction(set_missionCounter));
		L.RegVar("rewardOver", new LuaCSFunction(get_rewardOver), new LuaCSFunction(set_rewardOver));
		L.RegVar("ObjectType", new LuaCSFunction(get_ObjectType), null);
		L.RegVar("BelongForce", new LuaCSFunction(get_BelongForce), new LuaCSFunction(set_BelongForce));
		L.RegVar("BelongCorps", new LuaCSFunction(get_BelongCorps), new LuaCSFunction(set_BelongCorps));
		L.RegVar("BelongCity", new LuaCSFunction(get_BelongCity), new LuaCSFunction(set_BelongCity));
		L.RegVar("BelongTroop", new LuaCSFunction(get_BelongTroop), new LuaCSFunction(set_BelongTroop));
		L.RegVar("Official", new LuaCSFunction(get_Official), new LuaCSFunction(set_Official));
		L.RegVar("Exp", new LuaCSFunction(get_Exp), null);
		L.RegVar("Level", new LuaCSFunction(get_Level), new LuaCSFunction(set_Level));
		L.RegVar("Father", new LuaCSFunction(get_Father), new LuaCSFunction(set_Father));
		L.RegVar("Mother", new LuaCSFunction(get_Mother), new LuaCSFunction(set_Mother));
		L.RegVar("SpouseList", new LuaCSFunction(get_SpouseList), null);
		L.RegVar("BrotherList", new LuaCSFunction(get_BrotherList), null);
		L.RegVar("LikePersonList", new LuaCSFunction(get_LikePersonList), null);
		L.RegVar("HatePersonList", new LuaCSFunction(get_HatePersonList), null);
		L.RegVar("SpearLv", new LuaCSFunction(get_SpearLv), null);
		L.RegVar("HalberdLv", new LuaCSFunction(get_HalberdLv), null);
		L.RegVar("CrossbowLv", new LuaCSFunction(get_CrossbowLv), null);
		L.RegVar("HorseLv", new LuaCSFunction(get_HorseLv), null);
		L.RegVar("WaterLv", new LuaCSFunction(get_WaterLv), null);
		L.RegVar("MachineLv", new LuaCSFunction(get_MachineLv), null);
		L.RegVar("Command", new LuaCSFunction(get_Command), null);
		L.RegVar("Strength", new LuaCSFunction(get_Strength), null);
		L.RegVar("Intelligence", new LuaCSFunction(get_Intelligence), null);
		L.RegVar("Politics", new LuaCSFunction(get_Politics), null);
		L.RegVar("Glamour", new LuaCSFunction(get_Glamour), null);
		L.RegVar("IsValid", new LuaCSFunction(get_IsValid), null);
		L.RegVar("TroopsLimit", new LuaCSFunction(get_TroopsLimit), null);
		L.RegVar("MilitaryAbility", new LuaCSFunction(get_MilitaryAbility), null);
		L.RegVar("BaseCommerceAbility", new LuaCSFunction(get_BaseCommerceAbility), null);
		L.RegVar("BaseSecurityAbility", new LuaCSFunction(get_BaseSecurityAbility), null);
		L.RegVar("BaseTrainTroopAbility", new LuaCSFunction(get_BaseTrainTroopAbility), null);
		L.RegVar("BaseAgricultureAbility", new LuaCSFunction(get_BaseAgricultureAbility), null);
		L.RegVar("BaseBuildAbility", new LuaCSFunction(get_BaseBuildAbility), null);
		L.RegVar("BaseCreativeAbility", new LuaCSFunction(get_BaseCreativeAbility), null);
		L.RegVar("BaseSearchingAbility", new LuaCSFunction(get_BaseSearchingAbility), null);
		L.RegVar("BaseRecruitmentAbility", new LuaCSFunction(get_BaseRecruitmentAbility), null);
		L.RegVar("Age", new LuaCSFunction(get_Age), null);
		L.RegVar("IsFree", new LuaCSFunction(get_IsFree), null);
		L.RegVar("IsWild", new LuaCSFunction(get_IsWild), null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSango_Game_Person(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Sango.Game.Person obj = new Sango.Game.Person();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Sango.Game.Person.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HasItem(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			bool o = obj.HasItem(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPersonAgeUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.OnPersonAgeUpdate(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsAlliance(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<Sango.Game.BuildingBase>(L, 2))
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.BuildingBase arg0 = (Sango.Game.BuildingBase)ToLua.ToObject(L, 2);
				bool o = obj.IsAlliance(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Sango.Game.Troop>(L, 2))
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.Troop arg0 = (Sango.Game.Troop)ToLua.ToObject(L, 2);
				bool o = obj.IsAlliance(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.Force arg0 = (Sango.Game.Force)ToLua.CheckObject<Sango.Game.Force>(L, 2);
				Sango.Game.Force arg1 = (Sango.Game.Force)ToLua.CheckObject<Sango.Game.Force>(L, 3);
				bool o = obj.IsAlliance(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Sango.Game.Person.IsAlliance");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsEnemy(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<Sango.Game.BuildingBase>(L, 2))
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.BuildingBase arg0 = (Sango.Game.BuildingBase)ToLua.ToObject(L, 2);
				bool o = obj.IsEnemy(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Sango.Game.Troop>(L, 2))
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.Troop arg0 = (Sango.Game.Troop)ToLua.ToObject(L, 2);
				bool o = obj.IsEnemy(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.Force arg0 = (Sango.Game.Force)ToLua.CheckObject<Sango.Game.Force>(L, 2);
				Sango.Game.Force arg1 = (Sango.Game.Force)ToLua.CheckObject<Sango.Game.Force>(L, 3);
				bool o = obj.IsEnemy(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Sango.Game.Person.IsEnemy");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsSameForce(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<Sango.Game.BuildingBase>(L, 2))
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.BuildingBase arg0 = (Sango.Game.BuildingBase)ToLua.ToObject(L, 2);
				bool o = obj.IsSameForce(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Sango.Game.Troop>(L, 2))
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.Troop arg0 = (Sango.Game.Troop)ToLua.ToObject(L, 2);
				bool o = obj.IsSameForce(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Sango.Game.Person>(L, 2))
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.Person arg0 = (Sango.Game.Person)ToLua.ToObject(L, 2);
				bool o = obj.IsSameForce(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.Force arg0 = (Sango.Game.Force)ToLua.CheckObject<Sango.Game.Force>(L, 2);
				Sango.Game.Force arg1 = (Sango.Game.Force)ToLua.CheckObject<Sango.Game.Force>(L, 3);
				bool o = obj.IsSameForce(arg0, arg1);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Sango.Game.Person.IsSameForce");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnScenarioPrepare(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.OnScenarioPrepare(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnYearStart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			bool o = obj.OnYearStart(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateMission(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.UpdateMission(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMission(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.MissionType arg0 = (Sango.Game.MissionType)ToLua.CheckObject(L, 2, TypeTraits<Sango.Game.MissionType>.type);
			Sango.Game.SangoObject arg1 = (Sango.Game.SangoObject)ToLua.CheckObject<Sango.Game.SangoObject>(L, 3);
			int arg2 = (int)LuaDLL.luaL_checkinteger(L, 4);
			obj.SetMission(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearMission(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			obj.ClearMission();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnNewTurn(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			bool o = obj.OnTurnStart(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnTurnStart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			bool o = obj.OnForceTurnStart(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TransformToCity(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.City arg0 = (Sango.Game.City)ToLua.CheckObject<Sango.Game.City>(L, 2);
			obj.TransformToCity(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeCorps(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.Corps arg0 = (Sango.Game.Corps)ToLua.CheckObject<Sango.Game.Corps>(L, 2);
			Sango.Game.Corps o = obj.ChangeCorps(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ChangeCity(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.City arg0 = (Sango.Game.City)ToLua.CheckObject<Sango.Game.City>(L, 2);
			Sango.Game.City o = obj.ChangeCity(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int JobRecuritPerson(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.Person arg0 = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 2);
			obj.JobRecuritPerson(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int JoinToForce(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.City arg0 = (Sango.Game.City)ToLua.CheckObject<Sango.Game.City>(L, 2);
			bool o = obj.JoinToForce(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LeaveToWild(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			obj.LeaveToWild();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Persuade(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			Sango.Game.Person arg0 = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 2);
			bool o = obj.Persuade(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BeCaptive(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<Sango.Game.City>(L, 2))
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.City arg0 = (Sango.Game.City)ToLua.ToObject(L, 2);
				Sango.Game.Person o = obj.BeCaptive(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<Sango.Game.Troop>(L, 2))
			{
				Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
				Sango.Game.Troop arg0 = (Sango.Game.Troop)ToLua.ToObject(L, 2);
				Sango.Game.Person o = obj.BeCaptive(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Sango.Game.Person.BeCaptive");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GainExp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Person obj = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.GainExp(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_familyNameID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.familyNameID;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index familyNameID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_familyName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			string ret = obj.familyName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index familyName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_giveNameID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.giveNameID;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index giveNameID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_giveName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			string ret = obj.giveName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index giveName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_nickNameID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.nickNameID;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index nickNameID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_nickName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			string ret = obj.nickName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index nickName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_descriptionID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.descriptionID;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index descriptionID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_description(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			string ret = obj.description;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index description on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_headIconID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.headIconID;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index headIconID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_imageID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.imageID;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index imageID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_sex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.sex;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_yearAvailable(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.yearAvailable;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index yearAvailable on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_beFinded(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			bool ret = obj.beFinded;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index beFinded on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_yearBorn(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.yearBorn;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index yearBorn on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_yearDead(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.yearDead;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index yearDead on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_compatibility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.compatibility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index compatibility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_state(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.state;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index state on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_loyalty(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.loyalty;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loyalty on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_merit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.merit;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index merit on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_command(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue ret = obj.command;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index command on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_strength(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue ret = obj.strength;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index strength on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_intelligence(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue ret = obj.intelligence;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index intelligence on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_politics(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue ret = obj.politics;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index politics on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_glamour(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue ret = obj.glamour;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index glamour on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_consanguinity(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.consanguinity;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index consanguinity on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_sonList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.SangoObjectList<Sango.Game.Person> ret = obj.sonList;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sonList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_spearLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue ret = obj.spearLv;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index spearLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_halberdLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue ret = obj.halberdLv;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index halberdLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_crossbowLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue ret = obj.crossbowLv;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index crossbowLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_horseLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue ret = obj.horseLv;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index horseLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_waterLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue ret = obj.waterLv;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index waterLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_machineLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue ret = obj.machineLv;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index machineLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_actionFlag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.BitCheck32 ret = obj.actionFlag;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index actionFlag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FeatureList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.SangoObjectList<Sango.Game.Feature> ret = obj.FeatureList;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FeatureList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_itemStore(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.ItemStore ret = obj.itemStore;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index itemStore on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_troopsLimitExtra(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.troopsLimitExtra;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index troopsLimitExtra on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_skill(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			ushort ret = obj.skill;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index skill on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_missionType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.missionType;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index missionType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_missionTarget(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.missionTarget;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index missionTarget on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_missionCounter(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.missionCounter;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index missionCounter on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_rewardOver(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			bool ret = obj.rewardOver;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rewardOver on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ObjectType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.SangoObjectType ret = obj.ObjectType;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ObjectType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BelongForce(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Force ret = obj.BelongForce;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BelongForce on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BelongCorps(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Corps ret = obj.BelongCorps;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BelongCorps on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BelongCity(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.City ret = obj.BelongCity;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BelongCity on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BelongTroop(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Troop ret = obj.BelongTroop;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BelongTroop on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Official(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Official ret = obj.Official;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Official on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Exp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.Exp;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Exp on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Level(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonLevel ret = obj.Level;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Level on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Father(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Person ret = obj.Father;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Father on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Mother(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Person ret = obj.Mother;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Mother on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SpouseList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.SangoObjectList<Sango.Game.Person> ret = obj.SpouseList;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SpouseList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BrotherList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.SangoObjectList<Sango.Game.Person> ret = obj.BrotherList;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BrotherList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LikePersonList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.SangoObjectList<Sango.Game.Person> ret = obj.LikePersonList;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index LikePersonList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HatePersonList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.SangoObjectList<Sango.Game.Person> ret = obj.HatePersonList;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HatePersonList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SpearLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.SpearLv;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SpearLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HalberdLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.HalberdLv;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HalberdLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CrossbowLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.CrossbowLv;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CrossbowLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HorseLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.HorseLv;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index HorseLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WaterLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.WaterLv;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index WaterLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MachineLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.MachineLv;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MachineLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Command(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.Command;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Command on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Strength(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.Strength;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Strength on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Intelligence(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.Intelligence;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Intelligence on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Politics(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.Politics;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Politics on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Glamour(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.Glamour;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Glamour on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsValid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			bool ret = obj.IsValid;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsValid on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TroopsLimit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.TroopsLimit;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index TroopsLimit on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MilitaryAbility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.MilitaryAbility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MilitaryAbility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseCommerceAbility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.BaseCommerceAbility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseCommerceAbility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseSecurityAbility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.BaseSecurityAbility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseSecurityAbility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseTrainTroopAbility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.BaseTrainTroopAbility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseTrainTroopAbility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseAgricultureAbility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.BaseAgricultureAbility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseAgricultureAbility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseBuildAbility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.BaseBuildAbility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseBuildAbility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseCreativeAbility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.BaseCreativeAbility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseCreativeAbility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseSearchingAbility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.BaseSearchingAbility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseSearchingAbility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BaseRecruitmentAbility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.BaseRecruitmentAbility;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BaseRecruitmentAbility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Age(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int ret = obj.Age;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Age on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsFree(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			bool ret = obj.IsFree;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsFree on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsWild(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			bool ret = obj.IsWild;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsWild on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_familyNameID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.familyNameID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index familyNameID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_familyName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.familyName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index familyName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_giveNameID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.giveNameID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index giveNameID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_giveName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.giveName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index giveName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_nickNameID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.nickNameID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index nickNameID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_nickName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.nickName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index nickName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_descriptionID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.descriptionID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index descriptionID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_description(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.description = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index description on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_headIconID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.headIconID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index headIconID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_imageID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.imageID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index imageID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_sex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.sex = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_yearAvailable(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.yearAvailable = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index yearAvailable on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_beFinded(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.beFinded = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index beFinded on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_yearBorn(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.yearBorn = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index yearBorn on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_yearDead(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.yearDead = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index yearDead on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_compatibility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.compatibility = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index compatibility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_state(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.state = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index state on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_loyalty(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.loyalty = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index loyalty on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_merit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.merit = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index merit on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_command(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue arg0 = (Sango.Game.PersonAttributeValue)ToLua.CheckObject<Sango.Game.PersonAttributeValue>(L, 2);
			obj.command = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index command on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_strength(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue arg0 = (Sango.Game.PersonAttributeValue)ToLua.CheckObject<Sango.Game.PersonAttributeValue>(L, 2);
			obj.strength = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index strength on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_intelligence(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue arg0 = (Sango.Game.PersonAttributeValue)ToLua.CheckObject<Sango.Game.PersonAttributeValue>(L, 2);
			obj.intelligence = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index intelligence on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_politics(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue arg0 = (Sango.Game.PersonAttributeValue)ToLua.CheckObject<Sango.Game.PersonAttributeValue>(L, 2);
			obj.politics = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index politics on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_glamour(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAttributeValue arg0 = (Sango.Game.PersonAttributeValue)ToLua.CheckObject<Sango.Game.PersonAttributeValue>(L, 2);
			obj.glamour = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index glamour on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_consanguinity(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.consanguinity = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index consanguinity on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_sonList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.SangoObjectList<Sango.Game.Person> arg0 = (Sango.Game.SangoObjectList<Sango.Game.Person>)ToLua.CheckObject<Sango.Game.SangoObjectList<Sango.Game.Person>>(L, 2);
			obj.sonList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index sonList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_spearLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue arg0 = (Sango.Game.PersonAbilityValue)ToLua.CheckObject<Sango.Game.PersonAbilityValue>(L, 2);
			obj.spearLv = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index spearLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_halberdLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue arg0 = (Sango.Game.PersonAbilityValue)ToLua.CheckObject<Sango.Game.PersonAbilityValue>(L, 2);
			obj.halberdLv = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index halberdLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_crossbowLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue arg0 = (Sango.Game.PersonAbilityValue)ToLua.CheckObject<Sango.Game.PersonAbilityValue>(L, 2);
			obj.crossbowLv = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index crossbowLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_horseLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue arg0 = (Sango.Game.PersonAbilityValue)ToLua.CheckObject<Sango.Game.PersonAbilityValue>(L, 2);
			obj.horseLv = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index horseLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_waterLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue arg0 = (Sango.Game.PersonAbilityValue)ToLua.CheckObject<Sango.Game.PersonAbilityValue>(L, 2);
			obj.waterLv = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index waterLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_machineLv(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonAbilityValue arg0 = (Sango.Game.PersonAbilityValue)ToLua.CheckObject<Sango.Game.PersonAbilityValue>(L, 2);
			obj.machineLv = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index machineLv on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_actionFlag(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.BitCheck32 arg0 = (Sango.Game.BitCheck32)ToLua.CheckObject<Sango.Game.BitCheck32>(L, 2);
			obj.actionFlag = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index actionFlag on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_FeatureList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.SangoObjectList<Sango.Game.Feature> arg0 = (Sango.Game.SangoObjectList<Sango.Game.Feature>)ToLua.CheckObject<Sango.Game.SangoObjectList<Sango.Game.Feature>>(L, 2);
			obj.FeatureList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index FeatureList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_itemStore(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.ItemStore arg0 = (Sango.Game.ItemStore)ToLua.CheckObject<Sango.Game.ItemStore>(L, 2);
			obj.itemStore = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index itemStore on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_troopsLimitExtra(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.troopsLimitExtra = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index troopsLimitExtra on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_skill(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			ushort arg0 = (ushort)LuaDLL.luaL_checkinteger(L, 2);
			obj.skill = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index skill on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_missionType(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.missionType = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index missionType on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_missionTarget(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.missionTarget = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index missionTarget on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_missionCounter(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.missionCounter = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index missionCounter on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_rewardOver(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.rewardOver = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index rewardOver on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BelongForce(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Force arg0 = (Sango.Game.Force)ToLua.CheckObject<Sango.Game.Force>(L, 2);
			obj.BelongForce = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BelongForce on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BelongCorps(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Corps arg0 = (Sango.Game.Corps)ToLua.CheckObject<Sango.Game.Corps>(L, 2);
			obj.BelongCorps = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BelongCorps on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BelongCity(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.City arg0 = (Sango.Game.City)ToLua.CheckObject<Sango.Game.City>(L, 2);
			obj.BelongCity = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BelongCity on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BelongTroop(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Troop arg0 = (Sango.Game.Troop)ToLua.CheckObject<Sango.Game.Troop>(L, 2);
			obj.BelongTroop = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BelongTroop on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Official(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Official arg0 = (Sango.Game.Official)ToLua.CheckObject<Sango.Game.Official>(L, 2);
			obj.Official = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Official on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Level(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.PersonLevel arg0 = (Sango.Game.PersonLevel)ToLua.CheckObject<Sango.Game.PersonLevel>(L, 2);
			obj.Level = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Level on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Father(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Person arg0 = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 2);
			obj.Father = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Father on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Mother(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Person obj = (Sango.Game.Person)o;
			Sango.Game.Person arg0 = (Sango.Game.Person)ToLua.CheckObject<Sango.Game.Person>(L, 2);
			obj.Mother = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Mother on a nil value");
		}
	}
}

