//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Game_Render_WindowEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.Game.Render.WindowEvent), typeof(Sango.Game.Render.RenderEventBase));
		L.RegFunction("Enter", new LuaCSFunction(Enter));
		L.RegFunction("Exit", new LuaCSFunction(Exit));
		L.RegFunction("New", new LuaCSFunction(_CreateSango_Game_Render_WindowEvent));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("windowName", new LuaCSFunction(get_windowName), new LuaCSFunction(set_windowName));
		L.RegVar("arg1", new LuaCSFunction(get_arg1), new LuaCSFunction(set_arg1));
		L.RegVar("arg2", new LuaCSFunction(get_arg2), new LuaCSFunction(set_arg2));
		L.RegVar("arg3", new LuaCSFunction(get_arg3), new LuaCSFunction(set_arg3));
		L.RegVar("arg4", new LuaCSFunction(get_arg4), new LuaCSFunction(set_arg4));
		L.RegVar("arg5", new LuaCSFunction(get_arg5), new LuaCSFunction(set_arg5));
		L.RegVar("arg6", new LuaCSFunction(get_arg6), new LuaCSFunction(set_arg6));
		L.RegVar("arg7", new LuaCSFunction(get_arg7), new LuaCSFunction(set_arg7));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSango_Game_Render_WindowEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Sango.Game.Render.WindowEvent obj = new Sango.Game.Render.WindowEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Sango.Game.Render.WindowEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Enter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)ToLua.CheckObject<Sango.Game.Render.WindowEvent>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.Enter(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Exit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)ToLua.CheckObject<Sango.Game.Render.WindowEvent>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.Exit(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_windowName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			string ret = obj.windowName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index windowName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_arg1(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object ret = obj.arg1;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg1 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_arg2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object ret = obj.arg2;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_arg3(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object ret = obj.arg3;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg3 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_arg4(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object ret = obj.arg4;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg4 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_arg5(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object ret = obj.arg5;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg5 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_arg6(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object ret = obj.arg6;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg6 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_arg7(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object ret = obj.arg7;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg7 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_windowName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.windowName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index windowName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_arg1(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.arg1 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg1 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_arg2(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.arg2 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg2 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_arg3(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.arg3 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg3 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_arg4(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.arg4 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg4 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_arg5(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.arg5 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg5 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_arg6(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.arg6 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg6 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_arg7(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.WindowEvent obj = (Sango.Game.Render.WindowEvent)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.arg7 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index arg7 on a nil value");
		}
	}
}

