//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Sango_Game_Render_TroopMoveEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Sango.Game.Render.TroopMoveEvent), typeof(Sango.Game.Render.RenderEventBase));
		L.RegFunction("Enter", new LuaCSFunction(Enter));
		L.RegFunction("Exit", new LuaCSFunction(Exit));
		L.RegFunction("IsVisible", new LuaCSFunction(IsVisible));
		L.RegFunction("Update", new LuaCSFunction(Update));
		L.RegFunction("New", new LuaCSFunction(_CreateSango_Game_Render_TroopMoveEvent));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("troop", new LuaCSFunction(get_troop), new LuaCSFunction(set_troop));
		L.RegVar("start", new LuaCSFunction(get_start), new LuaCSFunction(set_start));
		L.RegVar("dest", new LuaCSFunction(get_dest), new LuaCSFunction(set_dest));
		L.RegVar("isLastMove", new LuaCSFunction(get_isLastMove), new LuaCSFunction(set_isLastMove));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSango_Game_Render_TroopMoveEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Sango.Game.Render.TroopMoveEvent obj = new Sango.Game.Render.TroopMoveEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Sango.Game.Render.TroopMoveEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Enter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)ToLua.CheckObject<Sango.Game.Render.TroopMoveEvent>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.Enter(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Exit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)ToLua.CheckObject<Sango.Game.Render.TroopMoveEvent>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			obj.Exit(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsVisible(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)ToLua.CheckObject<Sango.Game.Render.TroopMoveEvent>(L, 1);
			bool o = obj.IsVisible();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)ToLua.CheckObject<Sango.Game.Render.TroopMoveEvent>(L, 1);
			Sango.Game.Scenario arg0 = (Sango.Game.Scenario)ToLua.CheckObject<Sango.Game.Scenario>(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			bool o = obj.Update(arg0, arg1);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_troop(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)o;
			Sango.Game.Troop ret = obj.troop;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index troop on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_start(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)o;
			Sango.Game.Cell ret = obj.start;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index start on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_dest(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)o;
			Sango.Game.Cell ret = obj.dest;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dest on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isLastMove(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)o;
			bool ret = obj.isLastMove;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isLastMove on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_troop(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)o;
			Sango.Game.Troop arg0 = (Sango.Game.Troop)ToLua.CheckObject<Sango.Game.Troop>(L, 2);
			obj.troop = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index troop on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_start(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)o;
			Sango.Game.Cell arg0 = (Sango.Game.Cell)ToLua.CheckObject<Sango.Game.Cell>(L, 2);
			obj.start = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index start on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_dest(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)o;
			Sango.Game.Cell arg0 = (Sango.Game.Cell)ToLua.CheckObject<Sango.Game.Cell>(L, 2);
			obj.dest = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index dest on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isLastMove(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Sango.Game.Render.TroopMoveEvent obj = (Sango.Game.Render.TroopMoveEvent)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.isLastMove = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index isLastMove on a nil value");
		}
	}
}

